// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQSqXW2ASrT7UNMb5iMZAmWRtwEQWb43k',
    appId: '1:1017429531631:web:1c2b59b4e9460234f2b41a',
    messagingSenderId: '1017429531631',
    projectId: 'test-f01ba',
    authDomain: 'test-f01ba.firebaseapp.com',
    storageBucket: 'test-f01ba.appspot.com',
    measurementId: 'G-LK0K95NF1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiKTAUwd7kRtUqQCwdtVxfr4G3FHiivbs',
    appId: '1:1017429531631:android:15e7f06540407b5af2b41a',
    messagingSenderId: '1017429531631',
    projectId: 'test-f01ba',
    storageBucket: 'test-f01ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm4PMltokYqO744mrfBVeQujxXGU3A4Fs',
    appId: '1:1017429531631:ios:8fb8cbaf5874f7f8f2b41a',
    messagingSenderId: '1017429531631',
    projectId: 'test-f01ba',
    storageBucket: 'test-f01ba.appspot.com',
    iosClientId: '1017429531631-0i54faa5va9lcukbht5hk68ojl84sdog.apps.googleusercontent.com',
    iosBundleId: 'com.example.flitterFirebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm4PMltokYqO744mrfBVeQujxXGU3A4Fs',
    appId: '1:1017429531631:ios:8fb8cbaf5874f7f8f2b41a',
    messagingSenderId: '1017429531631',
    projectId: 'test-f01ba',
    storageBucket: 'test-f01ba.appspot.com',
    iosClientId: '1017429531631-0i54faa5va9lcukbht5hk68ojl84sdog.apps.googleusercontent.com',
    iosBundleId: 'com.example.flitterFirebaseTest',
  );
}
